language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - CORE_BRANCH=stable10
    - APP=diagnostics
  matrix:
    - DB=sqlite;

branches:
  only:
    - master

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP

before_script:
  - cd apps/$APP

script:
  # Run phpunit tests
  - cd tests
  - ../../../lib/composer/bin/phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=mysql;CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql;CORE_BRANCH=master
    - php: 7.2
      env: DB=mysql